// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorChatling.Data.DBContextFiles
{
    public partial class Chats
    {
        public Chats()
        {
            Messages = new HashSet<Messages>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Messages> Messages { get; set; }
    }
}