// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorChatling.Data.DBContextFiles
{
    public partial class ChatUser
    {
        public int IdUser { get; set; }
        public int IdChat { get; set; }

        public virtual Chats IdChatNavigation { get; set; }
        public virtual Users IdUserNavigation { get; set; }
    }
}