// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorChatling.Data.DBContextFiles
{
    public partial class Messages
    {
        public Messages()
        {
            InverseIdReplyMessageNavigation = new HashSet<Messages>();
        }

        public int Id { get; set; }
        public int IdChat { get; set; }
        public int IdUser { get; set; }
        public int? IdReplyMessage { get; set; }
        public int? IdReplyUser { get; set; }
        public string MsgText { get; set; }
        public DateTime? MsgTime { get; set; }
        public bool? IsEdited { get; set; }
        public bool? IsVisibleToCreator { get; set; }
        public bool? IsReplyVisibleToGroup { get; set; }

        public virtual Chats IdChatNavigation { get; set; }
        public virtual Messages IdReplyMessageNavigation { get; set; }
        public virtual Users IdUserNavigation { get; set; }
        public virtual ICollection<Messages> InverseIdReplyMessageNavigation { get; set; }
    }
}